export const ON_HABITS_CHANGE= "ON_HABITS_CHANGE";
export const ON_HOBBIES_CHANGE = "ON_HOBBIES_CHANGE";
export const ON_LOCATION_CHANGE= "ON_LOCATION_CHANGE";
export const ON_BUDGET_CHANGE = "ON_BUDGET_CHANGE";
export const ON_SUBMIT = "ON_SUBMIT";